<a href="https://colab.research.google.com/github/eehujnihs21-stack/app0320/blob/main/251209.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr=np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
import numpy as np

arr = np.array(["박원빈", "박성훈", "오시온", "안건호", "엄성현"])
print(arr)

['박원빈' '박성훈' '오시온' '안건호' '엄성현']


In [ ]:
import numpy as np

arr = np.array([["박원빈", "박성훈", "오시온"], ["안건호", "엄성현", "제임스"]])
print(arr)


[['박원빈' '박성훈' '오시온']
 ['안건호' '엄성현' '제임스']]


In [ ]:
import numpy as np

arr = np.array([[["박원빈", "박성훈", "오시온"],["안건호", "엄성현", "제임스"],["지우", "유하", "이안"]],
                [["박원빈", "박성훈", "오시온"],["안건호", "엄성현", "제임스"],["지우", "유하", "이안"]],
                [["박원빈", "박성훈", "오시온"],["안건호", "엄성현", "제임스"],["지우", "유하", "이안"]]])
print(arr)

[[['박원빈' '박성훈' '오시온']
  ['안건호' '엄성현' '제임스']
  ['지우' '유하' '이안']]

 [['박원빈' '박성훈' '오시온']
  ['안건호' '엄성현' '제임스']
  ['지우' '유하' '이안']]

 [['박원빈' '박성훈' '오시온']
  ['안건호' '엄성현' '제임스']
  ['지우' '유하' '이안']]]


In [ ]:
zeros_1d = np.zeros(5)
print(zeros_1d)

[0. 0. 0. 0. 0.]


In [ ]:
zeros_2d = np.zeros((3, 4))
print(zeros_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones_1d = np.ones(5)
print(ones_1d)

[1. 1. 1. 1. 1.]


In [ ]:
ones_2d = np.ones((2, 3))
print(ones_2d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
full_array = np.full((3, 3), 5)
print(full_array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
a=np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
a=np.logspace(np.log10(10),np.log10(100),5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [ ]:
a=np.logspace(1,2,5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(f"배열: {arr}")

print(f"첫 번째 요소: {arr[0]}")

print(f"마지막 요소: {arr[-1]}")

print(f"세 번째 요소: {arr[2]}")

배열: [10 20 30 40 50]
첫 번째 요소: 10
마지막 요소: 50
세 번째 요소: 30


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(f"배열: {arr}")
print(f"arr[-1]: {arr[1]}")
print(f"arr[-2]: {arr[-2]}")
print(f"arr[-3]: {arr[-3]}")

배열: [10 20 30 40 50]
arr[-1]: 20
arr[-2]: 40
arr[-3]: 30


In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"원본 배열: {arr}")

print(f"arr[2:7]: {arr[2:7]}")

print(f"arr[:5]: {arr[:5]}")

print(f"arr[5:]: {arr[5:]}")

print(f"arr[:]: {arr[:]}")

원본 배열: [0 1 2 3 4 5 6 7 8 9]
arr[2:7]: [2 3 4 5 6]
arr[:5]: [0 1 2 3 4]
arr[5:]: [5 6 7 8 9]
arr[:]: [0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"원본 배열: {arr}")

print(f"arr[::2]: {arr[::2]}")

print(f"arr[1:8:2]: {arr[1:8:2]}")

print(f"arr[::-1]: {arr[::-1]}")

print(f"arr[::-2]: {arr[::-2]}")

원본 배열: [0 1 2 3 4 5 6 7 8 9]
arr[::2]: [0 2 4 6 8]
arr[1:8:2]: [1 3 5 7]
arr[::-1]: [9 8 7 6 5 4 3 2 1 0]
arr[::-2]: [9 7 5 3 1]


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2차원 배열:")
print(arr_2d)

print(f"arr_2d[0,0]: {arr_2d[0,0]}")

print(f"arr_2d[1, 2]: {arr_2d[1, 2]}")

print(f"arr_2d[-1, -1]: {arr_2d[-1, -1]}")

2차원 배열:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_2d[0,0]: 1
arr_2d[1, 2]: 6
arr_2d[-1, -1]: 9


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2차원 배열:")
print(arr_2d)

print(f"첫 번째 행: {arr_2d[0, :]}")

print(f"두 번째 열: {arr_2d[:, 1]}")

print(f"마지막 행: {arr_2d[-1,:]}")

print(f"첫 번째 행: {arr_2d[:, -1]}")

2차원 배열:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
첫 번째 행: [1 2 3]
두 번째 열: [2 5 8]
마지막 행: [7 8 9]
첫 번째 행: [3 6 9]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2차원 배열:")
print(arr_2d)

print(f"arr_2d[0:2, 0:2]:")
print(arr_2d[0:2, 0:2])

print(f"arr_2d[:, 0:2]:")
print(arr_2d[:, 0:2])

print(f"arr_2d[0:2, :]:")
print(arr_2d[0:2, :])

2차원 배열:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_2d[0:2, 0:2]:
[[1 2]
 [4 5]]
arr_2d[:, 0:2]:
[[1 2]
 [4 5]
 [7 8]]
arr_2d[0:2, :]:
[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"원본 배열:")
print(arr_2d)

print(f"arr_2d[::2, ::2]:")
print(arr_2d[::2, ::2])

print(f"arr_2d[::2, ::1]:")
print(arr_2d[::2, ::1])

원본 배열:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_2d[::2, ::2]:
[[1 3]
 [7 9]]
arr_2d[::2, ::1]:
[[1 2 3]
 [7 8 9]]


In [ ]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3차원 배열:")
print(arr_3d)
print(f"shape: {arr_3d.shape}")

print(f"arr_3d[0, 0, 0]: {arr_3d[0, 0, 0]}")

print(f"arr_3d[1, 1, 0]: {arr_3d[1, 1, 0]}")

print(f"첫 번째 깊이:")
print(arr_3d[0, :, :])

3차원 배열:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)
arr_3d[0, 0, 0]: 1
arr_3d[1, 1, 0]: 7
첫 번째 깊이:
[[1 2]
 [3 4]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"원본 배열: {arr}")

mask = arr > 5
print(f"조건 (arr > 5): {mask}")
print(f"5보다 큰 요소들 {arr[mask]}")

even_mask = arr % 2 == 0
print(f"짝수인 요소들: {arr[even_mask]}")

multiple_of_3_mask = arr % 3 == 0
print(f"3의 배수인 요소들: {arr[multiple_of_3_mask]}")

원본 배열: [ 1  2  3  4  5  6  7  8  9 10]
조건 (arr > 5): [False False False False False  True  True  True  True  True]
5보다 큰 요소들 [ 6  7  8  9 10]
짝수인 요소들: [ 2  4  6  8 10]
3의 배수인 요소들: [3 6 9]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"원본 배열: {arr}")

condition = (arr > 3) & (arr < 8)
print(f"3보다 크고 8보다 작은 요소들 {arr[condition]}")

condition2 = (arr % 2 == 0) | (arr % 5 == 0)
print(f"2의 배수이거나 5의 배수인 요소들 {arr[condition2]}")

원본 배열: [ 1  2  3  4  5  6  7  8  9 10]
3보다 크고 8보다 작은 요소들 [4 5 6 7]
2의 배수이거나 5의 배수인 요소들 [ 2  4  5  6  8 10]
